version: '3.1'

services:

  db:
    image: icorrea/postgresql:11.6-alpine3.10
    environment:
      POSTGRES_PASSWORD: senha123
    networks:
      - dsa_net
    volumes:
      - ~/srv/postgresql/v12_1/paises:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    env_file:
      - environment.env
    image: icorrea/api_paises_rest:1.0-flask_restplus
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "5000:5000"
    depends_on:
      - db
    networks:
      - dsa_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "italiviocorrea@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - dsa_net

networks:
  dsa_net:
    external: true